# Generated by Django 5.1 on 2024-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='current_feelslike',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
